from exceptions.exception_validation_error import ValidationError

class NonExistentUser(ValidationError):
    pass
